FEU-19/holiday-maker

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- server/.eslintrc.json
- server/.gitignore
- server/package-lock.json
- server/package.json
Added eslint, prettier & airbnb configs/dependencies.
> eslint-prettier-airbnb dev deps added

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/App.test.js
- server/.eslintrc.json
- server/server.js
Changed config of eslint/prettier.
> Eslint hotfix

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/index.js
Babel vs eslint issues fixed for create-react-app.
> eslint hotfix(v2) for client

- client/src/AppRouter.js
- client/src/components/common/Checkbox/Checkbox.js
- client/src/index.js
- client/src/views/Residence.js
- client/src/views/Residence/Carousel.js
- client/src/views/Residence/Residence.js
- client/src/views/Residence/styles.js
grid & carousel for detailed residence view
> carousel working

- client/src/components/common/Modal/Modal.js
- client/src/index.js
- client/src/views/Main.js
> Miami modal

- client/src/components/Checkout/Spinner.js
Hej,
Spinner animation klart. Vi har kollat det med Mohamed. Det funkar bra. Funkionalität kan vi lägga till senare.
> added Spinner to Checkout folder

- client/src/components/Residence/ResidenceInformation.js
- client/src/views/Residence.js
> Acapulco residence information

- client/src/AppRouter.js
- client/src/components/common/DropDown/DropDown.js
Dropdown with Material-UIs FormControl.
> Miami dropdown

- client/src/components/Registration/RegisterButton.js
- client/src/components/Registration/RenderInputs.js
- client/src/components/Registration/RenderMsg.js
- client/src/components/common/Header/Header.js
> Registration

- client/src/components/Main/SearchContainer/SearchContainer.js
- client/src/components/Main/SearchContainer/SelectAmountOfAdults.js
- client/src/components/Main/SearchContainer/SelectAmountOfChildren.js
Det är kodningen längst ner ni ska titta på, jag fick göra en commit innan så jag kunde jämföra med Annas selecter.
> Blue hawaii select amount of adults

- client/src/components/Residence/GeneralInformation.js
- client/src/components/Residence/ResidenceInformation.js
- client/src/views/Residence.js
Added general information about residence
> Added generalInformation

- client/package.json
- client/src/components/Residence/RoomType.js
- server/server.js
> Acapulco roomtype

- client/src/components/Residence/RoomCard.js
- client/src/components/Residence/RoomPrice.js
det ser ut som om jag har ändrat allt i koden men är bara ESlint som flyttat runt det tror jag!
> added SEK and edited layout of pricecard

- client/src/AppRouter.js
> remove path

- client/src/views/Residence.js
> updated hotelId with mongodb compass

- client/src/components/common/DropDown/DropDown.js
- client/src/views/Details/BookingForm.js
Merged DropDown with BookingForm
> Merged DropDown with BookingForm

- client/src/components/Residence/Carousel.js
- client/src/components/Residence/HotelCarousel.js
- client/src/components/Residence/Img.js
- client/src/components/Residence/MiniImages.js
- client/src/components/Residence/ModalDialogButton.js
- client/src/components/Residence/RoomType.js
- client/src/components/Residence/SimpleDialog.js
- client/src/views/Residence.js
> finally fixed

- client/src/components/Residence/RoomCard.js
- client/src/components/Residence/RoomPrice.js
- client/src/views/Residence.js
- holiday-maker.code-workspace
> added price change

- client/src/components/Residence/Carousel.js
- client/src/components/Residence/HotelCarousel.js
- client/src/components/Residence/Img.js
- client/src/components/Residence/MiniImages.js
- client/src/components/Residence/ModalDialogButton.js
- client/src/components/Residence/RoomCard.js
- client/src/components/Residence/SimpleDialog.js
- client/src/views/Residence.js
now has more and bigger pics and each room has correct pic.
> Acapulco dialog2

- client/src/components/Residence/GeneralInformation.js
- client/src/components/Residence/HotelCarousel.js
- client/src/components/Residence/MiniImages.js
- client/src/components/Residence/RoomCard.js
- client/src/components/Residence/RoomCardMapper.js
- client/src/components/Residence/RoomPrice.js
- client/src/components/Residence/SimpleDialog.js
> bug hunt successfull

- client/src/views/Residence.js
> bookmark fix

- client/src/components/Checkout/Payment.js
- client/src/config/constants.js
- server/controllers/orders.js
- server/models/Order.js
- server/routes/orders.js
> Miami order post
